
# anki note settings
deck_name=Japanese::Vocabulary::Mined
model_name=Lapis
sentence_field=Sentence
audio_field=SentenceAudio
image_field=Picture
miscinfo_enable=no

# snapshot
snapshot_quality=80
snapshot_width=-2
snapshot_height=720

# audio
audio_padding=0.15
audio_bitrate=128k

audio_format=opus
opus_container=opus

# tags
note_tag=アニメ::%n
