
# Window rules

windowrule = match:class kitty, opacity 1.0 0.7
windowrule = match:title Spotify, opacity 0.95
windowrule = match:class mpv, float yes
windowrule = match:class mpv, pseudo yes
windowrule = match:title Picture-in-Picture, float yes
windowrule = match:title Picture-in-Picture, pin yes

windowrule = match:class PureRef, no_blur yes

windowrule = match:title Pomodorolm, float yes

windowrule = match:class com.saivert.pwvucontrol, float yes
windowrule = match:class com.saivert.pwvucontrol, size 455 546, 
windowrule = match:class com.saivert.pwvucontrol, move 1447 50
windowrule = match:class com.saivert.pwvucontrol, pin yes



windowrule = match:class anki, idle_inhibit yes
windowrule = match:initial_class nz.co.mega.megasync, float yes
windowrule = match:initial_class nz.co.mega.megasync, size 402 564
windowrule = match:initial_class nz.co.mega.megasync, move 1447 50
windowrule = match:initial_class nz.co.mega.megasync, stay_focused yes

windowrule = match:initial_class flameshot, no_anim yes

